app/assets/stylesheets/ship_listing.scss
app/assets/stylesheets/voyage_and_ship.scss
app/views/includes/ship/_tile.html.erb
app/views/pages/ship_listing.html.erb

ship_listings page is responsive now

[Feature] add responsive to ship listings

---

app/assets/stylesheets/custom.scss
app/assets/stylesheets/global.scss
app/views/includes/_footer.html.erb
app/views/pages/home.html.erb

Trello:
- https://trello.com/c/99ZHCAhK/30-style-newsletter-box
Fix styles for footer email send section

[Fix] footer email send section

---

app/assets/stylesheets/header/header.scss
app/views/includes/_header.html.erb

Trello: 
- https://trello.com/c/dsLdbDBz/22-add-phone-number-to-header
added telephone number

[Feature] telephone number

---

.gitignore
app/admin/order.rb
app/models/order.rb
db/migrate/20170322164826_add_fields_to_orders.rb
db/schema.rb

[Trello ticket](https://trello.com/c/BjaFX93Z/32-modify-order-model)
Added: 
- deposit_invoice_link:string
- deposit_invoice:attachment (use paperclip and validate it is a pdf)
- payment_invoice_link:string
- payment_invoice:attachment (use paperclip and validate it is a pdf)
- payment_summary:text
- AA functional

[Fix] Modify Order model

---

app/assets/stylesheets/voyage_and_ship.scss
app/views/includes/_header.html.erb

Trello:
- https://trello.com/c/FbUPqEnR/39-fx-star-on-voyage-tile
Fix positions of stars on homepage

[Fix] positions of stars

---

app/assets/stylesheets/application.scss

Trello:
- https://trello.com/c/QL8LCp4N/57-reordering-css
I deleted repetition styles and now we can change the order of the css connection

[Fix] reordering styles

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/fix_theme.scss

**Trello:**
- https://trello.com/c/VNcRGy4b/43-bug-center-icons-vertically
- https://trello.com/c/CxBV4tvU/56-bug-not-responsive-for-icons
Fix Icons

[Fix] icons

---

app/admin/activity.rb
app/assets/stylesheets/application.scss
app/assets/stylesheets/fix_theme.scss
app/controllers/checkout_controller.rb
app/controllers/order_items_controller.rb
app/models/order.rb
app/models/order_item.rb

Trello tickets: 
https://trello.com/c/g5IRrduA/53-bug-add-extra-activity-should-not-be-valid-if-qty-is-0
https://trello.com/c/2htN70h5/52-bug-any-activity-with-is-mandatory-true-should-be-automatically-included-in-the-order
any activity with .is_mandatory == true automatically included in the order
fixed issue "add extra activity should not be valid if qty is 0"
fixed issue if qty negative meaning get total price negative value

[Bug] Fixed extras page

---

app/assets/javascripts/search.js
app/assets/stylesheets/search.scss
app/views/includes/search/_checkbox_filter_item.html.erb
app/views/includes/search/_radio_button_filter_item.html.erb
app/views/includes/search/_ship_filters.html.erb
app/views/includes/search/_voyage_filters.html.erb
app/views/search/ships.html.erb
app/views/search/voyages.html.erb

Trello:
https://trello.com/c/fUzG7yBv/11-bug-style-search-ui-selectors
Fix search/filters

[Fix] filters

---

app/assets/stylesheets/checkout.scss
app/assets/stylesheets/global.scss
app/views/checkout/cart.html.erb
app/views/checkout/confirm.html.erb

Trello ticket: https://trello.com/c/dzr69j1O/54-bug-remove-reserve-from-checkout-cart
- Moved 'Reserve' button from cart to confirm page

[Bug] Moved 'Reserve' button from cart to confirm page

---

app/controllers/checkout_controller.rb
app/models/activity.rb
app/models/order.rb
app/models/order_item.rb
app/views/checkout/extras.html.erb
app/views/includes/checkout/_cart_table_row.html.erb
db/migrate/20170406133856_add_not_null_to_activities_is_mandatory.rb
db/schema.rb

Trello tickets: 
https://trello.com/c/2htN70h5/52-bug-any-activity-with-is-mandatory-true-should-be-automatically-included-in-the-order
https://trello.com/c/v72K9xPn/62-bug-should-not-be-able-to-remove-mandatory-activity-at-checkout-cart

[Bug] Fixed extra activities

---

app/assets/stylesheets/custom.scss
app/assets/stylesheets/fix_theme.scss
app/assets/stylesheets/global.scss
app/assets/stylesheets/header/header.scss
app/views/includes/_header.html.erb

Trello: 
- https://trello.com/c/os2X72OZ/58-top-menu-spacing
- https://trello.com/c/06B7OYJ4/119-bug-hero-images-on-tablets-is-unproportional
Fix top menu

[Fix] top menu

---

app/assets/stylesheets/fix_theme.scss
app/assets/stylesheets/registration.scss

Trello 
- https://trello.com/c/nzjoasL2/59-account-creation-error-styling
Corrected error message

[Fix] corrected error massage in sign up page

---

app/controllers/dashboard_controller.rb

Trello ticket: https://trello.com/c/gboUsuNt/102-bug-links-to-invoices-not-showing
Fixed problem, when links to invoices not showing

[BUG] links to invoices not showing

---

app/assets/stylesheets/registration.scss
app/views/devise/registrations/new.html.erb

Trello: 
- https://trello.com/c/zp1obFLW/60-styling-of-toggles-on-sign-up
fix checkbo

[Fix] checkboxes

---

app/assets/stylesheets/global.scss
app/decorators/activity_decorator.rb
app/views/includes/_horizontal_tile_text.html.erb

Trello ticket: https://trello.com/c/i4ik58GQ/129-bug-activities-not-showing-price-at-add-extras-page
Added price at "Add extras page"

[BUG] Activities not showing price at Add extras page

---

app/assets/javascripts/messages.js
app/views/devise/registrations/new.html.erb
app/views/includes/_messages.html.erb
app/views/layouts/application.html.erb
app/views/layouts/dashboard.html.erb

Trello ticket: https://trello.com/c/tz6uCpkY/48-bug-move-success-flash-to-top-right-with-green-border
All flash messages moved to right side.

[BUG] Flash messages

---

app/views/includes/_important_docs_antarctica.html.erb
app/views/includes/_important_docs_arctic.html.erb

Trello ticket: https://trello.com/c/xQWzssS3/94-bug-google-doc-links
Uploaded documents to s3, changed links

[BUG] Uploaded documents to s3, changed links

---

app/helpers/application_helper.rb
app/views/includes/_footer.html.erb

Trello ticket: https://trello.com/c/oPva81f1/122-bug-footer-links
Made the text in footer links

[Bug] footer links

---

app/assets/stylesheets/global.scss
app/assets/stylesheets/voyages.scss
app/views/voyages/show.html.erb

Trello: 
- https://trello.com/c/ITucIltt/124-bug-voyage-info-box
- https://trello.com/c/yR67tB8l/154-fix-mobile-version-on-voyages-page
added outline voyage msg

[Fix] added outline voyage msg

---

app/assets/stylesheets/fix_theme.scss

Trello : 
- https://trello.com/c/L9c519xP/108-bug-basic-search-design-not-inline-with-original-design
corrected dropbox, added icons, increased the sliders

[Fix] corrected dropbox, added icons, increased the sliders

---

app/assets/stylesheets/fix_theme.scss
app/views/includes/_footer.html.erb
app/views/pages/home.html.erb

Trello:
- https://trello.com/c/tM9O1Jxz/143-bug-corrections
Corrected first letter iExpedition

[Fix] Corrected first letter

---

app/assets/javascripts/application.js
app/assets/javascripts/dashboard/personal_details.js
app/assets/javascripts/expand-all-btn.js
app/assets/stylesheets/global.scss
app/views/dashboard/confirmed_itinerary.html.erb
app/views/includes/contact_us/_booking_tab.html.erb
app/views/includes/contact_us/_cancellations_tab.html.erb
app/views/includes/contact_us/_expedition_info_tab.html.erb
app/views/includes/contact_us/_my_account_tab.html.erb
app/views/includes/contact_us/_vassels_tab.html.erb
app/views/includes/voyage/_itinerary_tab.html.erb

Trello: 
- https://trello.com/c/9JqgtRjT/63-bug-implement-expand-all-collapse-all 
Added buttons for expand/collapse all tabs

[Feature] added buttons for expand/collapse all tabs

---

app/views/pages/home.html.erb

Trello: 
- https://trello.com/c/JDap1852/121-bug-homepage-featured-voyages 
voyages replaced

[Fix] replace voyages

---

app/assets/stylesheets/fix_theme.scss
app/views/includes/_horizontal_tile_left.html.erb
app/views/includes/_horizontal_tile_right.html.erb

Trello ticket: https://trello.com/c/8GAyRy4L/150-bug-labels
Added Label hightligh

[Fix] Label hightligh

---

app/views/includes/_footer.html.erb
app/views/pages/about_us.html.erb

Trello ticket: https://trello.com/c/XwxgywaO/40-add-live-links-to-social-media-icons
Added instagram link to "follow us" blocks

[Fix] Added instagram link to follow us blocks

---

app/helpers/application_helper.rb
app/views/includes/_footer.html.erb
app/views/includes/voyage/_overview_tab.html.erb

Trello ticket: https://trello.com/c/FsJz7qx1/70-mod-single-supplement-picks-up-higher-value-supplement-can-we-look-at-printing-lower-value
Single supplement now choosen average value

[Fix] Single supplement picks up higher value supplement.

---

app/assets/stylesheets/destinations.scss
app/assets/stylesheets/fix_theme.scss
app/assets/stylesheets/voyages.scss

Trello: 
- https://trello.com/c/TDuI9EuB/24-add-and-position-destination-watermark 
corrected watermark img

[Fix] watermark image

---

app/assets/stylesheets/print/application.scss
app/controllers/print_controller.rb
app/views/dashboard/confirmed_itinerary.html.erb
app/views/includes/cabin/_view_tile.html.erb
app/views/layouts/print.html.erb
app/views/print/itinerary.html.erb
config/initializers/assets.rb
config/routes.rb

Trello ticket: https://trello.com/c/6US89dHb/64-feature-print-itinerary

[Feature] Print itinerary

---

app/views/checkout/extras.html.erb
app/views/includes/_alternating_horizontal_tiles.html.erb

Trello: 
- https://trello.com/c/Z4Y09G01/157-checkout-extras
added message when no options extras are available

[Fix] message in extras

---

.gitignore
Gemfile
Gemfile.lock
app/admin/order.rb
app/assets/javascripts/application.js
app/assets/stylesheets/admin.css
app/assets/stylesheets/global.scss
app/models/order.rb
app/models/voucher.rb
app/views/dashboard/confirmed_itinerary.html.erb
app/views/includes/_footer.html.erb
app/views/includes/_important_docs_antarctica.html.erb
app/views/includes/_important_docs_arctic.html.erb
app/views/includes/_social_links.html.erb
app/views/includes/dashboard/_important_information.html.erb
app/views/includes/voyage/_gallery_tab.html.erb
config/initializers/active_admin.rb
config/initializers/assets.rb
db/migrate/20170420084438_add_important_information_to_order.rb
db/migrate/20170420093331_create_vouchers.rb
db/migrate/20170421112007_remove_important_information_from_order.rb
db/schema.rb
test/factories/vouchers.rb
test/models/voucher_test.rb

Trello ticket:  https://trello.com/c/BXHkamX7/160-add-important-information-and-vouchers
Added Vouchers and important information

[Feature] Vouchers and important information

---

app/assets/javascripts/contact_requests.js
app/assets/stylesheets/global.scss
app/models/contact_request.rb
app/views/pages/contact_us.html.erb

Trello:
- https://trello.com/c/575zhhxi/113-contact-us
fix contact us

[Fix] contact us

---

Gemfile
Gemfile.lock
app/controllers/dashboard_controller.rb
app/mailers/application_mailer.rb
app/mailers/user_mailer.rb
app/views/dashboard/confirmed_itinerary.html.erb
app/views/dashboard/error.js.erb
app/views/dashboard/success.js.erb
app/views/includes/_reusable_search_form.html.erb
app/views/includes/search/_top_search_form.html.erb
app/views/user_mailer/send_itinerary_to_email.html.erb
config/initializers/mime_types.rb
config/initializers/wicked_pdf.rb
config/routes.rb
test/mailers/previews/user_mailer_preview.rb
test/mailers/user_mailer_test.rb

Trello ticket: https://trello.com/c/ZPRzPC06/133-bug-send-to-email
Added ability to send itinerary to email

[BUG] Send to email

---

app/helpers/application_helper.rb
app/views/includes/_header.html.erb

Trello ticket: https://trello.com/c/n4BNXGNN/161-empty-cart-after-checkout
Empty cart after checkout

[Fix] Empty cart after checkout
